---  
- name:   Update All Packages
  apt:   update_cache=yes upgrade=dist state=latest
    
- name:  Install Essential tools
  apt: name={{ item }} state=installed
  with_items:
    - screen
    - vim
    - wget

